### ISSUE TITLE
How could the model be conditioned on image classes?

### ISSUE THREAD

**Issue by janvainer** [chrischute/glow#5]
Hey, thank you very much for this nice repository! I was wondering, what would be the most convenient way to condition Glow model on image classes?

**Comment by chrischute** [comment]
I would recommend doing what they describe in the appendix D of [the paper](https://arxiv.org/pdf/1807.03039.pdf):

1. "Add a class dependent prior at the top-most level." E.g. rather than unit gaussian, you might choose a different mean per class. When sampling, just sample your noise from the distribution for the class you want to condition on.
2. (Probably less important, would try just implementing 1 first). "Add a classification loss to predict the class label from the second last layer of the encoder, with a weight of λ = 0.01." So you would add a 10-way class prediction module to the model, with input from the second-to-last layer. Then add a corresponding cross-entropy loss with coefficient of 0.01 (the original loss has coefficient of 1 or 0.99).

Hope that helps!

**Comment by janvainer** [comment]
Hi, thanks for the reply. I did not notice the appendix D of the paper! It makes a good sense to condition on class dependent prior. With the second option... by the second-to-last layer is meant the layer just before the latent variable or just before the image output?

**Comment by chrischute** [comment]
No problem - Just before the latent variable
