### ISSUE TITLE
Affine coupling forward

### ISSUE THREAD

**Issue by balassbals** [chrischute/glow#9]
Should not line num 38 in *coupling .py*  be 

`x_change = (x_change * s.exp()) + t` 

instead of

`x_change = (x_change + t) * s.exp()`

**Comment by chrischute** [comment]
Please see [this issue](https://github.com/chrischute/real-nvp/issues/4) in RealNVP (inspiration for the Glow coupling layer).

The main reason it's different is to match the [official implementation](https://github.com/openai/glow/blob/eaff2177693a5d84a1cf8ae19e8e0441715b82f8/model.py#L377-L378). When there were discrepancies between paper and code, I chose the authors' code, since that's where the results come from.
